export const tags = {
  tags: [
    'test',
    'butt',
    'dragons',
    'training',
    'tag1',
    'tags',
    'as',
    'tag2',
    'coffee',
    'animation',
    'baby',
    'money',
    'japan',
    'caramel',
    'flowers',
    'cars',
    'happiness',
    'cookies',
    'sugar',
    'sushi',
  ],
};

export const articles = {
  articles: [
    {
      title: 'TESTING',
      slug: 'testing-g9bv0u',
      body: 'Oh lalala',
      createdAt: '2020-04-20T15:45:02.499Z',
      updatedAt: '2020-04-20T15:45:02.499Z',
      tagList: [],
      description: 'TESTING',
      author: {
        username: 'luiscm88',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: 'Helloo',
      slug: 'helloo-9w86wa',
      body: 'Param pan mar',
      createdAt: '2020-04-20T15:34:49.513Z',
      updatedAt: '2020-04-20T15:35:59.667Z',
      tagList: ['ddddd', 'bio'],
      description: 'wqt',
      author: {
        username: 'AAAqqqq',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'testing',
      slug: 'testing-s171lr',
      body: 'sv finvg dfvnjnv',
      createdAt: '2020-04-20T15:27:13.174Z',
      updatedAt: '2020-04-20T15:27:13.174Z',
      tagList: [],
      description: 'i am ',
      author: {
        username: 'irshadillias',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'Software Development Team Lead',
      slug: 'software-development-team-lead-gze5yi',
      body:
        'As a driving force in the development of enterprise and Internet technology who has rapidly grown into a global operation, delivering an unrivalled online experience to more than 45 million customers in 21 languages - my client is passionate about their brand, product, customers and employees, and want to meet highly motivated individuals who will share their vision and passion.\n\n\nThey are currently in need of a software development team lead who will be required to retain a good technical understanding of their systems and remain close to the solution being developed whilst assisting in driving the provision of a capable, reactive, motivated and delivery focused team\n\n\nAs a suitable team lead, you will have : \n - Commercial experience with leading development teams\n -  Previous experience mentoring members of the team and ensuring distribution of knowledge\n - Been involved with developer’s appraisals and other performance feedback\n\n - The ability to actively plan and track works as prioritised by the product, project and development management\n\n -  Experience enforcing the governance around quality, rules, standards and processes within the team\n\n\nAll development is carried out in a n Agile/Scrum environment, so experience working in/enforcing this is highly desirable \n\n\nSound like you ? \n\n\nApply Directly or send your CV  to stephanie.hoffman@talentinternational.com \n\n',
      createdAt: '2020-04-20T15:16:14.569Z',
      updatedAt: '2020-04-20T15:16:14.569Z',
      tagList: [],
      description: 'manager',
      author: {
        username: 'irshadillias',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'sdsd',
      slug: 'sdsd-a1mcxl',
      body: 'dsd',
      createdAt: '2020-04-20T14:53:40.591Z',
      updatedAt: '2020-04-20T14:53:40.591Z',
      tagList: ['another', 'some tag2'],
      description: 'sdsd',
      author: {
        username: 'adsdsadsd',
        bio: 'sdsdsd',
        image: '',
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: 'test',
      slug: 'test-u9r5s5',
      body: 'test1234',
      createdAt: '2020-04-20T14:48:19.419Z',
      updatedAt: '2020-04-20T14:48:19.419Z',
      tagList: [],
      description: 'test123',
      author: {
        username: 'matthewwwwww',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'test',
      slug: 'test-hx4gaz',
      body: 'test',
      createdAt: '2020-04-20T14:45:06.963Z',
      updatedAt: '2020-04-20T14:45:06.963Z',
      tagList: [],
      description: 'test',
      author: {
        username: 'rocko123',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
    {
      title: 'tag',
      slug: 'tag-pu4ktw',
      body: 'tag',
      createdAt: '2020-04-20T14:44:38.874Z',
      updatedAt: '2020-04-20T14:44:38.874Z',
      tagList: [],
      description: 'test tag ',
      author: {
        username: 'ahmed5',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 0,
    },
    {
      title: 'sfdadf',
      slug: 'sfdadf-t0zui2',
      body: 'asdf',
      createdAt: '2020-04-20T14:39:49.040Z',
      updatedAt: '2020-04-20T14:39:49.040Z',
      tagList: [],
      description: 'asdfa',
      author: {
        username: 'me1010',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 2,
    },
    {
      title: 'article 370',
      slug: 'article-370-lt3tit',
      body: 'This is my article',
      createdAt: '2020-04-20T14:27:40.648Z',
      updatedAt: '2020-04-20T14:27:40.648Z',
      tagList: [],
      description: 'JK',
      author: {
        username: 'vivraut',
        bio: null,
        image: 'https://static.productionready.io/images/smiley-cyrus.jpg',
        following: false,
      },
      favorited: false,
      favoritesCount: 1,
    },
  ],
  articlesCount: 500,
};
